# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-17 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间'),
        ),
    ]
