# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-31 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200831_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='分类ID'),
        ),
    ]
