# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-17 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200817_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
