# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-19 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20200818_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
