# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-28 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='用户级别'),
        ),
    ]
